"""empty message

Revision ID: 55c326cf64ec
Revises: afd80e56a9e7
Create Date: 2020-12-18 09:55:08.450010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c326cf64ec'
down_revision = 'afd80e56a9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_uid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['author_uid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_uid')

    # ### end Alembic commands ###
